- docs/getting-started.md
- docs/service-loadbalancer.md
- exoscale/exoscale.go
- exoscale/loadbalancer.go
Allow to specify a default load-balancer zone
This avoids having to specify the mandatory `service.beta.kubernetes.io/exoscale-loadbalancer-zone` for each service.
> Allow to specify a default load-balancer zone

- .github/workflows/ci.yml
- integtest/run.bash
- integtest/test-nlb.bash
this PR increases the time before timeout
when for example we create an nlb service it is linked to an instance pool and in some cases when deleting the pool instance, the nlb service did not have time to delete itself properly, so it returns errors. That's why we have a `until_success()` function that allows us to restart the command for a given time
and in some cases there wasn't enough time
> Fix integration test

- exoscale/common.go
- exoscale/exoscale.go
This change fixes the `formatProviderID()` function to allow for
unprefixed Instance IDs (i.e. without `exoscale://`).
> Fix provider ID formatting logic

- Dockerfile
This allows to exec into the container for debugging but also gives more flexibility to fetch the API secrets (Vault for instance will provides the secret as a file so we need a shell to use that as an environment variable)
> Build images based on busybox

- exoscale/instances.go
As described [in the interface](https://github.com/kubernetes/cloud-provider/blob/release-1.17/cloud.go#L170:L173) the `InstanceID` method should return `"", cloudprovider.InstanceNotFound` if the instance does not exist.
I is implemented [the same way as for `InstanceExistsByProviderID`](b/262566639ce5a12d9db8691fa8857f0a3b7b5d72/exoscale/instances.go#L100)
This fixes an error while cleaning up nodes that have been deleted before being initialized:
```
E1207 13:42:09.098553       1 node_lifecycle_controller.go:149] error checking if node XXXXXXXXXXXXXXXXXXXXXXXXXX exists: API error ParamError 431 (ServerAPIException 9999): not found, query: apikey=EXOXXXXXXXXXXXXXXXXXXXXXXXX, command=listVirtualMachines, name=XXXXXXXXXXXXXXXXXXXXXXXXXX
```
> Instances.InstanceID: return InstanceNotFound if the instance doesn't exist

- exoscale/common.go
- exoscale/common_test.go
- exoscale/instances.go
- exoscale/zones.go
Currently the CCM fetches the ID of an instance by calling the Exoscale API and filtering by instance name.
It assumes the name of the Exoscale instance is the same as the name of the Kubernetes node.
By default the kubelet registers the node using the instance hostname, this can be overridden.
The hostname could also have been modified via cloud-init or another configuration tool making it different from the instance name.
After looking at closer at the Node object, it appears that the ID of the instance is already here.
```
apiVersion: v1
kind: Node
status:
nodeInfo:
systemUUID: 3f9944b0-2026-40aa-ac2e-ea277a64b101
```
After digging further into the code it turns out this id is taken from [/sys/class/dmi/id/product_uuid](https://github.com/google/cadvisor/blob/8450c56c21bc5406e2df79a2162 …
> Get the instance id from nodeObject.status.nodeInfo.systemUUID

- exoscale/loadbalancer.go
This change improves the Load Balancer controller logic when dealing
with clusters spanning multiple Nodepools/Instance Pools: if no Instance
Pool ID is specified in a Service annotations, the CCM will return an
explicit error if it finds multiple Instance Pools across the cluster
instead of assuming all Nodes are member of the same Instance Pool.
> Improve Load Balancer Instance Pool detection logic

- exoscale/client.go
- exoscale/common.go
- exoscale/common_test.go
- exoscale/exoscale.go
- exoscale/loadbalancer.go
- exoscale/log.go
- go.mod
- integtest/manifests/ccm.yml
- integtest/run.bash
- integtest/test-secret-file-reload.bash
- integtest/test.tf
- vendor/gopkg.in/fsnotify.v1/.editorconfig
- vendor/gopkg.in/fsnotify.v1/.gitignore
- vendor/gopkg.in/fsnotify.v1/.travis.yml
- vendor/gopkg.in/fsnotify.v1/AUTHORS
- vendor/gopkg.in/fsnotify.v1/CHANGELOG.md
- vendor/gopkg.in/fsnotify.v1/CONTRIBUTING.md
- vendor/gopkg.in/fsnotify.v1/LICENSE
- vendor/gopkg.in/fsnotify.v1/README.md
- vendor/gopkg.in/fsnotify.v1/fen.go
- vendor/gopkg.in/fsnotify.v1/fsnotify.go
- vendor/gopkg.in/fsnotify.v1/inotify.go
- vendor/gopkg.in/fsnotify.v1/inotify_poller.go
- vendor/gopkg.in/fsnotify.v1/kqueue.go
- vendor/gopkg.in/fsnotify.v1/open_mode_bsd.go
- vendor/gopkg.in/fsnotify.v1/open_mode_darwin.go
- vendor/gopkg.in/fsnotify.v1/windows.go
- vendor/modules.txt
Allows the Exoscale IAM secret to be loaded from a file, and automatically reloaded when this file is modified.
The configuration file is a JSON file that follows the format of the secret created by the [exoscale IAM vault plugin](https://github.com/exoscale/vault-plugin-secrets-exoscale)
Templating that file from vault ends up being as easy as:
```
{{- with secret "exoscale/apikey/my-ccm-role" -}}
{{ .Data | toJSON }}
{{- end }}
```
All call to egoscale are now guarded by a Mutex preventing its use while the IAM credential are being updated.
> Handle dynamic IAM secrets

- docs/service-loadbalancer.md
- exoscale/loadbalancer.go
- integtest/test.tf
This change fixes the NLB Service management logic, where previously
deploying a K8s Service to an external NLB would delete all the existing
NLB services that didn't use the same K8s Service ports as the new
Service uses.
Now, we only delete NLB services for unknown K8s Service ports if we're
on a dedicated NLB instance.
> Fix external NLB Service management logic 

- docs/service-loadbalancer.md
- exoscale/loadbalancer.go
- integtest/manifests/ingress-nginx.yml.tpl
- integtest/test-csr-validation.bash
This change adds support for K8s Services using
`externalTrafficPolicy:Local` and `healthCheckNodePort`, which allows
for configurations preserving the clients source IP address as described
in [this article][0].
[0]: https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-type-loadbalancer
> Add suport for healthCheckNodePort with NLB services

- exoscale/instances.go
- exoscale/loadbalancer.go
This change actually implements support for alternative Exoscale API
environment when specified via the `EXOSCALE_API_ENVIRONMENT`
environment variable.
> Honor Exoscale API environment settings

- .github/workflows/ci.yml
- integtest/test.tf
- Remove exoscale_security_group_rules in favor of exoscale_security_group_rule
- Replace local_file by local_sensitive_file
- Also fix the wrong go version used by the CI, keeping 1.17 instead of 1.18.
> Replace deprecated resources from integration tests

- docs/getting-started.md
- exoscale/client.go
- exoscale/client_test.go
- exoscale/exoscale.go
- exoscale/exoscale_config.go
- exoscale/exoscale_config_test.go
- exoscale/exoscale_test.go
- exoscale/instances.go
- exoscale/instances_config.go
- exoscale/instances_config_test.go
- exoscale/instances_test.go
- exoscale/loadbalancer.go
- exoscale/loadbalancer_config.go
- exoscale/loadbalancer_test.go
- exoscale/zones.go
- exoscale/zones_test.go
- integtest/manifests/ccm.yml.tpl
- integtest/test-csr-validation.bash
- integtest/test-init.bash
- integtest/test-nlb-external.bash
- integtest/test-nlb-ingress.bash
- integtest/test-node-labels.bash
- integtest/test.tf
```
* [go-1.17.8] cdufour@xps13-9380.cedric.exoscale.me:~/git/exoscale/exoscale-cloud-controller-manager (cedric/sc-45779/ccm-config-override)
$ make test
'/opt/cdufour/go/1.17.8/bin/go' test \
-race \
-mod vendor \
-timeout 15s \
\
github.com/exoscale/exoscale-cloud-controller-manager/exoscale
ok  	github.com/exoscale/exoscale-cloud-controller-manager/exoscale	(cached)
$ _EE_acc make test-integration | grep -E '(<<<|###|>>>|===|!!!)'
>>> DEPLOYING TEST CLUSTER INFRASTRUCTURE
exoscale_compute_instance.kube_master_node (remote-exec): ### Installing OS dependencies ...
exoscale_compute_instance.kube_master_node (remote-exec): ### Building Exoscale Cloud-Controller Manager (CCM) image ...
exoscale_compute_instance.kube_master_node (remote-exec): ### Bootstrapping Kubernetes control-plane ... …
```
> Add cloud-config (file) and instances override support

- exoscale/loadbalancer.go
Handles wrapped error from egoscale using `errors.Is`.
> loadbalancer: fix NotFound error handling

- exoscale/loadbalancer.go
Under some circumstances, a crash can happen because of a missing NLB id annotation.
Example stack trace:
```
E0701 08:18:11.056538  802594 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 347 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1ac2180?, 0x2efded0})
/home/phil/git/github.com/exoscale/exoscale-cloud-controller-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0006c8d20?})
/home/phil/git/github.com/exoscale/exoscale-cloud-controller-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x75
panic({0x1ac2180, 0x2efded0}) …
```
> Fix nil NLB-id crash

- test/README.md
- test/clean-up.sh
- test/lib/ccm-helpers.bash
- test/lib/test-setup.bash
- test/test-csr-validation.bash
```
$ ./run-kubeadm-tests.bash 
>>> TESTING API CREDENTIALS FILE RELOADING
<<< PASS
>>> TESTING SKS AGENT NODE CSR VALIDATION
<<< PASS
>>> TESTING CCM-MANAGED KUBERNETES NODE LABELS
<<< PASS
>>> TESTING CCM-MANAGED NLB INSTANCE
<<< PASS
>>> TESTING CCM WITH EXTERNAL NLB INSTANCE
<<< PASS
>>> TESTING CCM-MANAGED NODE EXPUNGING
<<< PASS
@ 2022-11-08 17:31:02 +0100
$ ./clean-up.sh 
removed 'api-creds'
removed 'api-creds.init'
removed 'api-creds.new'
removed 'ccm.log'
rm: cannot remove 'terraform-*/.env': No such file or directory
rm: cannot remove 'terraform-*/*.kubeconfig': No such file or directory
removed 'terraform-kubeadm/terraform-apply.log'
removed 'terraform-kubeadm/terraform-destroy.log'
removed 'terraform-kubeadm/terraform-init.log'
removed …
```
> test: some more guidance and verbosity

- exoscale/client_test.go
- exoscale/instances.go
- exoscale/instances_test.go
- exoscale/loadbalancer_test.go
- Instance Type label should be: `<family>.<size>` (only size was present in the label since apiv2 migration)
- Fix regex ( `.`, `-` and `_` were always replaced)
- Fix some tests (expected and actual were inverted)
> Fix instance-type label

- test/tests_2_nodes/test_202_nodes_files.py
FIX for `tests_2_nodes/test_202_nodes_files.py::test_kubeconfig_external_node FAILED` when `TEST_CCM_TYPE='sks'`
> test(acc): test_kubeconfig_external_node does not apply to SKS test type

- CHANGELOG.md
- exoscale/sks_agent_runner_node_csr_validation.go
- exoscale/sks_agent_runner_node_csr_validation_test.go
- test/show
- test/terraform/sks/nodes/main.tf
- K8s node name is always lowercase, DNSNames in CSR too, not Instance Name, CCM could not find an Instance when name contains uppercase 
- updates tests 
```
$ ./run  -t sks
INFO[run]: Running test type 'sks'
================================================================================ test session starts =================================================================================
platform linux -- Python 3.11.3, pytest-7.4.0, pluggy-1.3.0
rootdir: /home/jessica/git/exoscale/exoscale-cloud-controller-manager/test
configfile: pytest.ini
collected 69 items / 1 deselected / 68 selected
tests_0_environment/test_001_environment.py ..... …
```
> SKS: Fix CSR approval for instance name with uppercase

- .github/actions/build/action.yaml
According to my [last release attempt](https://github.com/exoscale/exoscale-cloud-controller-manager/actions/runs/7708071292/job/21006421996), there is a missing file: `.github/actions/build/action.yaml`.
See also [this change](https://github.com/exoscale/exoscale-cloud-controller-manager/pull/73/files#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34R20)
This prevents us from publishing new releases.
Locally ran commands from the definition.
> Add missing definition for CI builds

- .github/actions/build/action.yaml
- .github/workflows/main.yml
- .gitignore
- CHANGELOG.md
- Makefile
- Makefile.docker
```shell
❯ make docker
Cloning into 'go.mk'...
remote: Enumerating objects: 311, done.
remote: Counting objects: 100% (197/197), done.
remote: Compressing objects: 100% (95/95), done.
remote: Total 311 (delta 132), reused 138 (delta 93), pack-reused 114
Receiving objects: 100% (311/311), 62.32 KiB | 657.00 KiB/s, done.
Resolving deltas: 100% (175/175), done.
go.mk/version.mk:13: warning: overriding recipe for target 'get-version-tag'
/home/sauterp/src/github.com/exoscale/exoscale-cloud-controller-manager/go.mk/version.mk:13: warning: ignoring old recipe for target 'get-version-tag'
docker build --rm \
-t exoscale/cloud-controller-manager \
--build-arg VERSION="dev" \
--build-arg VCS_REF="12676f7c" \
--build-arg BUILD_DATE="2024-02-22T15:02:25Z" \
.
docker tag …
```
> go.mk: provide alternative to submodule approach

- CHANGELOG.md
- cmd/exoscale-cloud-controller-manager/main.go
> ccm-command: print returned error before exiting

- CHANGELOG.md
- docs/getting-started.md
The `make` binary shipping with Apple toolbelt is outdated and must be updated.
N/A
> chore(doc): add note about make for macOS users

- .gitignore
- exoscale/instances_test.go
instance.IPv6Enabled case was not covered nor instance.PrivateNetworkIDs
It's now solved
It's a prerequiside for sc-105769 which will change behavior of this function
> fix(sc-105769): add unittests on instances.NodeAddressesByProviderID

- CHANGELOG.md
- docs/service-loadbalancer.md
- exoscale/loadbalancer.go
- exoscale/loadbalancer_test.go
- test/README.md
- test/conftest.py
- test/resources/manifests/udp-echo.yaml
- test/terraform/sks/control-plane/main.tf
- test/terraform/sks/nodes/files.tf
- test/terraform/sks/nodes/outputs.tf
- test/tests_1_control_plane/test_103_control_plane_start.py
- test/tests_4_nlb/test_404_nlb_echo_udp.py
Update primarily loadbalancer.go to support UDP
- Removed check preventing creation of UDP LoadBalancer
- Modified updateLoadBalancer to make port/protocol combination is used as key instead of only port
- Check Port/Protocol combination during NLB deletion
- Added healthcheck annotation to make possible to provide a custom healthcheck port
- Added example to readme
Fixes #79
Added a test variant for NLB creation with UDP
```
❯ gmake test
go.mk/version.mk:13: warning: overriding recipe for target 'get-version-tag'
/Users/denis/Documents/GitHub/exoscale-cloud-controller-manager/go.mk/version.mk:13: warning: ignoring old recipe for target 'get-version-tag'
go.mk/version.mk:13: warning: overriding recipe for target 'get-version-tag' …
```
> Support UDP for LoadBalancer

- CHANGELOG.md
There are no breaking changes.
Implemented:
When using the API or IaaS its quite difficult to handle or specify ids. 
As explained here: https://github.com/exoscale/exoscale-cloud-controller-manager/issues/96
For referencing the load balancer, no new annotation was implemented. It just uses the existing annotation
```
service.beta.kubernetes.io/exoscale-loadbalancer-name
```
Will be used when it is specified AND `exoscale-loadbalancer-external` is set to true. 
If name is not specified `exoscale-loadbalancer-id` can still be used to achieve the same thing like before
Implemented
```
service.beta.kubernetes.io/exoscale-loadbalancer-service-sks-nodepool-name
```
when that is specified it will fill out the instancepool id automatically which matches the provided sks-nodepool name.
for that …
> Allow referencing the NLB and the target nodepool by name, and allow changing target instance-pool
